title: Basenana/NanaFS
description: FS-style workflow engine for unified data management with object-oriented approach and extensibility.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
