// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: cmd/apps/apis/fsapi/v1/fsapi-v1.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InboxClient is the client API for Inbox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InboxClient interface {
	QuickInbox(ctx context.Context, in *QuickInboxRequest, opts ...grpc.CallOption) (*QuickInboxResponse, error)
}

type inboxClient struct {
	cc grpc.ClientConnInterface
}

func NewInboxClient(cc grpc.ClientConnInterface) InboxClient {
	return &inboxClient{cc}
}

func (c *inboxClient) QuickInbox(ctx context.Context, in *QuickInboxRequest, opts ...grpc.CallOption) (*QuickInboxResponse, error) {
	out := new(QuickInboxResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Inbox/QuickInbox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InboxServer is the server API for Inbox service.
// All implementations should embed UnimplementedInboxServer
// for forward compatibility
type InboxServer interface {
	QuickInbox(context.Context, *QuickInboxRequest) (*QuickInboxResponse, error)
}

// UnimplementedInboxServer should be embedded to have forward compatible implementations.
type UnimplementedInboxServer struct {
}

func (UnimplementedInboxServer) QuickInbox(context.Context, *QuickInboxRequest) (*QuickInboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuickInbox not implemented")
}

// UnsafeInboxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InboxServer will
// result in compilation errors.
type UnsafeInboxServer interface {
	mustEmbedUnimplementedInboxServer()
}

func RegisterInboxServer(s grpc.ServiceRegistrar, srv InboxServer) {
	s.RegisterService(&Inbox_ServiceDesc, srv)
}

func _Inbox_QuickInbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuickInboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InboxServer).QuickInbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Inbox/QuickInbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InboxServer).QuickInbox(ctx, req.(*QuickInboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Inbox_ServiceDesc is the grpc.ServiceDesc for Inbox service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inbox_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.Inbox",
	HandlerType: (*InboxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuickInbox",
			Handler:    _Inbox_QuickInbox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/apps/apis/fsapi/v1/fsapi-v1.proto",
}

// EntriesClient is the client API for Entries service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntriesClient interface {
	GetEntryDetail(ctx context.Context, in *GetEntryDetailRequest, opts ...grpc.CallOption) (*GetEntryDetailResponse, error)
	CreateEntry(ctx context.Context, in *CreateEntryRequest, opts ...grpc.CallOption) (*CreateEntryResponse, error)
	UpdateEntry(ctx context.Context, in *UpdateEntryRequest, opts ...grpc.CallOption) (*UpdateEntryResponse, error)
	DeleteEntry(ctx context.Context, in *DeleteEntryRequest, opts ...grpc.CallOption) (*DeleteEntryResponse, error)
	GetGroupTree(ctx context.Context, in *GetGroupTreeRequest, opts ...grpc.CallOption) (*GetGroupTreeResponse, error)
	ListGroupChildren(ctx context.Context, in *ListGroupChildrenRequest, opts ...grpc.CallOption) (*ListGroupChildrenResponse, error)
	WriteFile(ctx context.Context, opts ...grpc.CallOption) (Entries_WriteFileClient, error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (Entries_ReadFileClient, error)
}

type entriesClient struct {
	cc grpc.ClientConnInterface
}

func NewEntriesClient(cc grpc.ClientConnInterface) EntriesClient {
	return &entriesClient{cc}
}

func (c *entriesClient) GetEntryDetail(ctx context.Context, in *GetEntryDetailRequest, opts ...grpc.CallOption) (*GetEntryDetailResponse, error) {
	out := new(GetEntryDetailResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Entries/GetEntryDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entriesClient) CreateEntry(ctx context.Context, in *CreateEntryRequest, opts ...grpc.CallOption) (*CreateEntryResponse, error) {
	out := new(CreateEntryResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Entries/CreateEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entriesClient) UpdateEntry(ctx context.Context, in *UpdateEntryRequest, opts ...grpc.CallOption) (*UpdateEntryResponse, error) {
	out := new(UpdateEntryResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Entries/UpdateEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entriesClient) DeleteEntry(ctx context.Context, in *DeleteEntryRequest, opts ...grpc.CallOption) (*DeleteEntryResponse, error) {
	out := new(DeleteEntryResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Entries/DeleteEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entriesClient) GetGroupTree(ctx context.Context, in *GetGroupTreeRequest, opts ...grpc.CallOption) (*GetGroupTreeResponse, error) {
	out := new(GetGroupTreeResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Entries/GetGroupTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entriesClient) ListGroupChildren(ctx context.Context, in *ListGroupChildrenRequest, opts ...grpc.CallOption) (*ListGroupChildrenResponse, error) {
	out := new(ListGroupChildrenResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Entries/ListGroupChildren", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entriesClient) WriteFile(ctx context.Context, opts ...grpc.CallOption) (Entries_WriteFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &Entries_ServiceDesc.Streams[0], "/api.v1.Entries/WriteFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &entriesWriteFileClient{stream}
	return x, nil
}

type Entries_WriteFileClient interface {
	Send(*WriteFileRequest) error
	CloseAndRecv() (*WriteFileResponse, error)
	grpc.ClientStream
}

type entriesWriteFileClient struct {
	grpc.ClientStream
}

func (x *entriesWriteFileClient) Send(m *WriteFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *entriesWriteFileClient) CloseAndRecv() (*WriteFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WriteFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *entriesClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (Entries_ReadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &Entries_ServiceDesc.Streams[1], "/api.v1.Entries/ReadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &entriesReadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Entries_ReadFileClient interface {
	Recv() (*ReadFileResponse, error)
	grpc.ClientStream
}

type entriesReadFileClient struct {
	grpc.ClientStream
}

func (x *entriesReadFileClient) Recv() (*ReadFileResponse, error) {
	m := new(ReadFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EntriesServer is the server API for Entries service.
// All implementations should embed UnimplementedEntriesServer
// for forward compatibility
type EntriesServer interface {
	GetEntryDetail(context.Context, *GetEntryDetailRequest) (*GetEntryDetailResponse, error)
	CreateEntry(context.Context, *CreateEntryRequest) (*CreateEntryResponse, error)
	UpdateEntry(context.Context, *UpdateEntryRequest) (*UpdateEntryResponse, error)
	DeleteEntry(context.Context, *DeleteEntryRequest) (*DeleteEntryResponse, error)
	GetGroupTree(context.Context, *GetGroupTreeRequest) (*GetGroupTreeResponse, error)
	ListGroupChildren(context.Context, *ListGroupChildrenRequest) (*ListGroupChildrenResponse, error)
	WriteFile(Entries_WriteFileServer) error
	ReadFile(*ReadFileRequest, Entries_ReadFileServer) error
}

// UnimplementedEntriesServer should be embedded to have forward compatible implementations.
type UnimplementedEntriesServer struct {
}

func (UnimplementedEntriesServer) GetEntryDetail(context.Context, *GetEntryDetailRequest) (*GetEntryDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntryDetail not implemented")
}
func (UnimplementedEntriesServer) CreateEntry(context.Context, *CreateEntryRequest) (*CreateEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntry not implemented")
}
func (UnimplementedEntriesServer) UpdateEntry(context.Context, *UpdateEntryRequest) (*UpdateEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEntry not implemented")
}
func (UnimplementedEntriesServer) DeleteEntry(context.Context, *DeleteEntryRequest) (*DeleteEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEntry not implemented")
}
func (UnimplementedEntriesServer) GetGroupTree(context.Context, *GetGroupTreeRequest) (*GetGroupTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupTree not implemented")
}
func (UnimplementedEntriesServer) ListGroupChildren(context.Context, *ListGroupChildrenRequest) (*ListGroupChildrenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroupChildren not implemented")
}
func (UnimplementedEntriesServer) WriteFile(Entries_WriteFileServer) error {
	return status.Errorf(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedEntriesServer) ReadFile(*ReadFileRequest, Entries_ReadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}

// UnsafeEntriesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntriesServer will
// result in compilation errors.
type UnsafeEntriesServer interface {
	mustEmbedUnimplementedEntriesServer()
}

func RegisterEntriesServer(s grpc.ServiceRegistrar, srv EntriesServer) {
	s.RegisterService(&Entries_ServiceDesc, srv)
}

func _Entries_GetEntryDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntryDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntriesServer).GetEntryDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Entries/GetEntryDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntriesServer).GetEntryDetail(ctx, req.(*GetEntryDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Entries_CreateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntriesServer).CreateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Entries/CreateEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntriesServer).CreateEntry(ctx, req.(*CreateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Entries_UpdateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntriesServer).UpdateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Entries/UpdateEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntriesServer).UpdateEntry(ctx, req.(*UpdateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Entries_DeleteEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntriesServer).DeleteEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Entries/DeleteEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntriesServer).DeleteEntry(ctx, req.(*DeleteEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Entries_GetGroupTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntriesServer).GetGroupTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Entries/GetGroupTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntriesServer).GetGroupTree(ctx, req.(*GetGroupTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Entries_ListGroupChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntriesServer).ListGroupChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Entries/ListGroupChildren",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntriesServer).ListGroupChildren(ctx, req.(*ListGroupChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Entries_WriteFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EntriesServer).WriteFile(&entriesWriteFileServer{stream})
}

type Entries_WriteFileServer interface {
	SendAndClose(*WriteFileResponse) error
	Recv() (*WriteFileRequest, error)
	grpc.ServerStream
}

type entriesWriteFileServer struct {
	grpc.ServerStream
}

func (x *entriesWriteFileServer) SendAndClose(m *WriteFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *entriesWriteFileServer) Recv() (*WriteFileRequest, error) {
	m := new(WriteFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Entries_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EntriesServer).ReadFile(m, &entriesReadFileServer{stream})
}

type Entries_ReadFileServer interface {
	Send(*ReadFileResponse) error
	grpc.ServerStream
}

type entriesReadFileServer struct {
	grpc.ServerStream
}

func (x *entriesReadFileServer) Send(m *ReadFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Entries_ServiceDesc is the grpc.ServiceDesc for Entries service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Entries_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.Entries",
	HandlerType: (*EntriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntryDetail",
			Handler:    _Entries_GetEntryDetail_Handler,
		},
		{
			MethodName: "CreateEntry",
			Handler:    _Entries_CreateEntry_Handler,
		},
		{
			MethodName: "UpdateEntry",
			Handler:    _Entries_UpdateEntry_Handler,
		},
		{
			MethodName: "DeleteEntry",
			Handler:    _Entries_DeleteEntry_Handler,
		},
		{
			MethodName: "GetGroupTree",
			Handler:    _Entries_GetGroupTree_Handler,
		},
		{
			MethodName: "ListGroupChildren",
			Handler:    _Entries_ListGroupChildren_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteFile",
			Handler:       _Entries_WriteFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadFile",
			Handler:       _Entries_ReadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cmd/apps/apis/fsapi/v1/fsapi-v1.proto",
}

// PropertiesClient is the client API for Properties service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PropertiesClient interface {
	AddProperty(ctx context.Context, in *AddPropertyRequest, opts ...grpc.CallOption) (*AddPropertyResponse, error)
	UpdateProperty(ctx context.Context, in *UpdatePropertyRequest, opts ...grpc.CallOption) (*UpdatePropertyResponse, error)
	DeleteProperty(ctx context.Context, in *DeletePropertyRequest, opts ...grpc.CallOption) (*DeletePropertyResponse, error)
}

type propertiesClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertiesClient(cc grpc.ClientConnInterface) PropertiesClient {
	return &propertiesClient{cc}
}

func (c *propertiesClient) AddProperty(ctx context.Context, in *AddPropertyRequest, opts ...grpc.CallOption) (*AddPropertyResponse, error) {
	out := new(AddPropertyResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Properties/AddProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertiesClient) UpdateProperty(ctx context.Context, in *UpdatePropertyRequest, opts ...grpc.CallOption) (*UpdatePropertyResponse, error) {
	out := new(UpdatePropertyResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Properties/UpdateProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertiesClient) DeleteProperty(ctx context.Context, in *DeletePropertyRequest, opts ...grpc.CallOption) (*DeletePropertyResponse, error) {
	out := new(DeletePropertyResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Properties/DeleteProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertiesServer is the server API for Properties service.
// All implementations should embed UnimplementedPropertiesServer
// for forward compatibility
type PropertiesServer interface {
	AddProperty(context.Context, *AddPropertyRequest) (*AddPropertyResponse, error)
	UpdateProperty(context.Context, *UpdatePropertyRequest) (*UpdatePropertyResponse, error)
	DeleteProperty(context.Context, *DeletePropertyRequest) (*DeletePropertyResponse, error)
}

// UnimplementedPropertiesServer should be embedded to have forward compatible implementations.
type UnimplementedPropertiesServer struct {
}

func (UnimplementedPropertiesServer) AddProperty(context.Context, *AddPropertyRequest) (*AddPropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProperty not implemented")
}
func (UnimplementedPropertiesServer) UpdateProperty(context.Context, *UpdatePropertyRequest) (*UpdatePropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProperty not implemented")
}
func (UnimplementedPropertiesServer) DeleteProperty(context.Context, *DeletePropertyRequest) (*DeletePropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProperty not implemented")
}

// UnsafePropertiesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertiesServer will
// result in compilation errors.
type UnsafePropertiesServer interface {
	mustEmbedUnimplementedPropertiesServer()
}

func RegisterPropertiesServer(s grpc.ServiceRegistrar, srv PropertiesServer) {
	s.RegisterService(&Properties_ServiceDesc, srv)
}

func _Properties_AddProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertiesServer).AddProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Properties/AddProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertiesServer).AddProperty(ctx, req.(*AddPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Properties_UpdateProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertiesServer).UpdateProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Properties/UpdateProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertiesServer).UpdateProperty(ctx, req.(*UpdatePropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Properties_DeleteProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertiesServer).DeleteProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Properties/DeleteProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertiesServer).DeleteProperty(ctx, req.(*DeletePropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Properties_ServiceDesc is the grpc.ServiceDesc for Properties service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Properties_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.Properties",
	HandlerType: (*PropertiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProperty",
			Handler:    _Properties_AddProperty_Handler,
		},
		{
			MethodName: "UpdateProperty",
			Handler:    _Properties_UpdateProperty_Handler,
		},
		{
			MethodName: "DeleteProperty",
			Handler:    _Properties_DeleteProperty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/apps/apis/fsapi/v1/fsapi-v1.proto",
}

// DocumentClient is the client API for Document service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentClient interface {
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	GetDocumentDetail(ctx context.Context, in *GetDocumentDetailRequest, opts ...grpc.CallOption) (*GetDocumentDetailResponse, error)
}

type documentClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentClient(cc grpc.ClientConnInterface) DocumentClient {
	return &documentClient{cc}
}

func (c *documentClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Document/ListDocuments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentClient) GetDocumentDetail(ctx context.Context, in *GetDocumentDetailRequest, opts ...grpc.CallOption) (*GetDocumentDetailResponse, error) {
	out := new(GetDocumentDetailResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Document/GetDocumentDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServer is the server API for Document service.
// All implementations should embed UnimplementedDocumentServer
// for forward compatibility
type DocumentServer interface {
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	GetDocumentDetail(context.Context, *GetDocumentDetailRequest) (*GetDocumentDetailResponse, error)
}

// UnimplementedDocumentServer should be embedded to have forward compatible implementations.
type UnimplementedDocumentServer struct {
}

func (UnimplementedDocumentServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedDocumentServer) GetDocumentDetail(context.Context, *GetDocumentDetailRequest) (*GetDocumentDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentDetail not implemented")
}

// UnsafeDocumentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentServer will
// result in compilation errors.
type UnsafeDocumentServer interface {
	mustEmbedUnimplementedDocumentServer()
}

func RegisterDocumentServer(s grpc.ServiceRegistrar, srv DocumentServer) {
	s.RegisterService(&Document_ServiceDesc, srv)
}

func _Document_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Document/ListDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Document_GetDocumentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).GetDocumentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Document/GetDocumentDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).GetDocumentDetail(ctx, req.(*GetDocumentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Document_ServiceDesc is the grpc.ServiceDesc for Document service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Document_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.Document",
	HandlerType: (*DocumentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDocuments",
			Handler:    _Document_ListDocuments_Handler,
		},
		{
			MethodName: "GetDocumentDetail",
			Handler:    _Document_GetDocumentDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/apps/apis/fsapi/v1/fsapi-v1.proto",
}
