// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/configs/{group}": {
            "get": {
                "description": "List all configuration values in a group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configs"
                ],
                "summary": "List configs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config group",
                        "name": "group",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ListConfigResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/configs/{group}/{name}": {
            "get": {
                "description": "Retrieve a configuration value by group and name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configs"
                ],
                "summary": "Get config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config group",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ConfigResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Set a configuration value",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configs"
                ],
                "summary": "Set config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config group",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Set config request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SetConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.SetConfigResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a configuration value",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configs"
                ],
                "summary": "Delete config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config group",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteConfigResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/entries": {
            "put": {
                "description": "Update an existing entry's aliases",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entries"
                ],
                "summary": "Update entry",
                "parameters": [
                    {
                        "description": "Update entry request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.UpdateEntryRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Entry URI",
                        "name": "uri",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.EntryDetailResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new entry with specified URI, kind and optional configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entries"
                ],
                "summary": "Create a new entry",
                "parameters": [
                    {
                        "description": "Entry creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.CreateEntryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.EntryResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an entry by URI or ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entries"
                ],
                "summary": "Delete entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entry URI",
                        "name": "uri",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.EntryResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/entries/batch-delete": {
            "post": {
                "description": "Batch delete multiple entries by URI list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entries"
                ],
                "summary": "Delete entries",
                "parameters": [
                    {
                        "description": "Delete entries request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.DeleteEntriesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.DeleteEntriesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/entries/details": {
            "get": {
                "description": "Get detailed information of an entry by URI or ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entries"
                ],
                "summary": "Get entry details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entry URI",
                        "name": "uri",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.EntryDetailResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/entries/document": {
            "get": {
                "description": "Get document properties of an entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entries"
                ],
                "summary": "Get entry document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entry URI",
                        "name": "uri",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.DocumentPropertyResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update document properties (unread, marked) of an entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entries"
                ],
                "summary": "Update document property",
                "parameters": [
                    {
                        "description": "Update document request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.UpdateDocumentPropertyRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Entry URI",
                        "name": "uri",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.DocumentPropertyResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/entries/parent": {
            "put": {
                "description": "Move an entry to a new parent directory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entries"
                ],
                "summary": "Change entry parent",
                "parameters": [
                    {
                        "description": "Change parent request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.ChangeParentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.EntryResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/entries/property": {
            "get": {
                "description": "Get properties and tags of an entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entries"
                ],
                "summary": "Get entry property",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entry URI",
                        "name": "uri",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.PropertyResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update properties and tags of an entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entries"
                ],
                "summary": "Update entry property",
                "parameters": [
                    {
                        "description": "Update property request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.UpdatePropertyRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Entry URI",
                        "name": "uri",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.PropertyResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/entries/search": {
            "post": {
                "description": "Filter entries using CEL pattern matching with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entries"
                ],
                "summary": "Filter entries",
                "parameters": [
                    {
                        "description": "Filter entry request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.FilterEntryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.ListEntriesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/content": {
            "get": {
                "description": "Read file content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Read file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File URI",
                        "name": "uri",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File content",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Write file content via multipart upload",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Write file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File URI",
                        "name": "uri",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "file",
                        "description": "File content",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.WriteFileResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/groups/children": {
            "get": {
                "description": "List children entries of a group with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "List group children",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group URI",
                        "name": "uri",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order field",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Sort descending",
                        "name": "desc",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.ListEntriesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/groups/tree": {
            "get": {
                "description": "Retrieve the complete group tree structure",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "Get group tree",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group URI",
                        "name": "uri",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GroupTreeResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/messages": {
            "get": {
                "description": "Retrieve notifications/messages for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "List messages",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Include all messages (including read)",
                        "name": "all",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.ListMessagesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/messages/read": {
            "post": {
                "description": "Mark messages as read",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Read messages",
                "parameters": [
                    {
                        "description": "Read messages request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.ReadMessagesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.ReadMessagesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workflows": {
            "get": {
                "description": "Retrieve all available workflows",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflows"
                ],
                "summary": "List workflows",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.ListWorkflowsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflows"
                ],
                "summary": "Create workflow",
                "parameters": [
                    {
                        "description": "Create workflow request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateWorkflowRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.CreateWorkflowResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workflows/{id}": {
            "get": {
                "description": "Retrieve a specific workflow by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflows"
                ],
                "summary": "Get workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.WorkflowResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflows"
                ],
                "summary": "Update workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update workflow request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateWorkflowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.WorkflowResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a workflow by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflows"
                ],
                "summary": "Delete workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workflows/{id}/jobs": {
            "get": {
                "description": "Retrieve all jobs for a specific workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflows"
                ],
                "summary": "List workflow jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.ListWorkflowJobsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workflows/{id}/jobs/{jobId}": {
            "get": {
                "description": "Retrieve a specific job by workflow ID and job ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflows"
                ],
                "summary": "Get workflow job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.WorkflowJobResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workflows/{id}/jobs/{jobId}/cancel": {
            "post": {
                "description": "Cancel a workflow job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflows"
                ],
                "summary": "Cancel job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workflows/{id}/jobs/{jobId}/pause": {
            "post": {
                "description": "Pause a running workflow job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflows"
                ],
                "summary": "Pause job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workflows/{id}/jobs/{jobId}/resume": {
            "post": {
                "description": "Resume a paused workflow job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflows"
                ],
                "summary": "Resume job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workflows/{id}/trigger": {
            "post": {
                "description": "Manually trigger a workflow to run",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflows"
                ],
                "summary": "Trigger workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Trigger workflow request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.TriggerWorkflowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_apps_apis_rest_v1.TriggerWorkflowResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cmd_apps_apis_rest_v1.ChangeParentRequest": {
            "type": "object",
            "required": [
                "entry_uri",
                "new_entry_uri"
            ],
            "properties": {
                "entry_uri": {
                    "type": "string"
                },
                "exchange": {
                    "type": "boolean"
                },
                "new_entry_uri": {
                    "type": "string"
                },
                "replace": {
                    "type": "boolean"
                }
            }
        },
        "cmd_apps_apis_rest_v1.CreateEntryRequest": {
            "type": "object",
            "required": [
                "uri"
            ],
            "properties": {
                "document": {
                    "$ref": "#/definitions/types.DocumentProperties"
                },
                "filter": {
                    "$ref": "#/definitions/v1.FilterConfig"
                },
                "kind": {
                    "type": "string"
                },
                "properties": {
                    "$ref": "#/definitions/types.Properties"
                },
                "rss": {
                    "$ref": "#/definitions/v1.RssConfig"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "cmd_apps_apis_rest_v1.DeleteEntriesRequest": {
            "type": "object",
            "required": [
                "uri_list"
            ],
            "properties": {
                "uri_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "cmd_apps_apis_rest_v1.DeleteEntriesResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "cmd_apps_apis_rest_v1.DocumentProperty": {
            "type": "object",
            "properties": {
                "abstract": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "header_image": {
                    "type": "string"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "marked": {
                    "type": "boolean"
                },
                "notes": {
                    "type": "string"
                },
                "publish_at": {
                    "type": "string"
                },
                "site_name": {
                    "type": "string"
                },
                "site_url": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "unread": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "cmd_apps_apis_rest_v1.EntryDetail": {
            "type": "object",
            "properties": {
                "access": {
                    "$ref": "#/definitions/v1.Access"
                },
                "access_at": {
                    "type": "string"
                },
                "aliases": {
                    "type": "string"
                },
                "changed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "document": {
                    "$ref": "#/definitions/cmd_apps_apis_rest_v1.DocumentProperty"
                },
                "entry": {
                    "type": "integer"
                },
                "is_group": {
                    "type": "boolean"
                },
                "kind": {
                    "type": "string"
                },
                "modified_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "property": {
                    "$ref": "#/definitions/cmd_apps_apis_rest_v1.Property"
                },
                "size": {
                    "type": "integer"
                },
                "storage": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "cmd_apps_apis_rest_v1.EntryInfo": {
            "type": "object",
            "properties": {
                "access_at": {
                    "type": "string"
                },
                "changed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "document": {
                    "$ref": "#/definitions/cmd_apps_apis_rest_v1.DocumentProperty"
                },
                "entry": {
                    "type": "integer"
                },
                "is_group": {
                    "type": "boolean"
                },
                "kind": {
                    "type": "string"
                },
                "modified_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "cmd_apps_apis_rest_v1.FilterEntryRequest": {
            "type": "object",
            "required": [
                "cel_pattern"
            ],
            "properties": {
                "cel_pattern": {
                    "description": "CEL pattern for filtering",
                    "type": "string"
                },
                "order": {
                    "description": "Order direction (asc/desc)",
                    "type": "string"
                },
                "page": {
                    "description": "Page number",
                    "type": "integer"
                },
                "page_size": {
                    "description": "Page size",
                    "type": "integer"
                },
                "sort": {
                    "description": "Sort field",
                    "type": "string"
                }
            }
        },
        "cmd_apps_apis_rest_v1.ListEntriesResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cmd_apps_apis_rest_v1.EntryInfo"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/v1.PaginationInfo"
                }
            }
        },
        "cmd_apps_apis_rest_v1.ListMessagesResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cmd_apps_apis_rest_v1.Message"
                    }
                }
            }
        },
        "cmd_apps_apis_rest_v1.ListWorkflowJobsResponse": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cmd_apps_apis_rest_v1.WorkflowJobDetail"
                    }
                }
            }
        },
        "cmd_apps_apis_rest_v1.ListWorkflowsResponse": {
            "type": "object",
            "properties": {
                "workflows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cmd_apps_apis_rest_v1.WorkflowInfo"
                    }
                }
            }
        },
        "cmd_apps_apis_rest_v1.Message": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "cmd_apps_apis_rest_v1.Property": {
            "type": "object",
            "properties": {
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "cmd_apps_apis_rest_v1.ReadMessagesRequest": {
            "type": "object",
            "required": [
                "message_id_list"
            ],
            "properties": {
                "message_id_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "cmd_apps_apis_rest_v1.ReadMessagesResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "cmd_apps_apis_rest_v1.TriggerWorkflowRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                },
                "timeout": {
                    "type": "integer"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "cmd_apps_apis_rest_v1.TriggerWorkflowResponse": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string"
                }
            }
        },
        "cmd_apps_apis_rest_v1.UpdateDocumentPropertyRequest": {
            "type": "object",
            "properties": {
                "abstract": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "headerImage": {
                    "type": "string"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "marked": {
                    "type": "boolean"
                },
                "notes": {
                    "type": "string"
                },
                "publishAt": {
                    "type": "integer"
                },
                "site_name": {
                    "type": "string"
                },
                "site_url": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "unread": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "cmd_apps_apis_rest_v1.UpdateEntryRequest": {
            "type": "object",
            "properties": {
                "aliases": {
                    "type": "string"
                }
            }
        },
        "cmd_apps_apis_rest_v1.UpdatePropertyRequest": {
            "type": "object",
            "properties": {
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "cmd_apps_apis_rest_v1.WorkflowInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_triggered_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "queue_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "cmd_apps_apis_rest_v1.WorkflowJobDetail": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "finish_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "queue_name": {
                    "type": "string"
                },
                "start_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.WorkflowJobStep"
                    }
                },
                "target": {
                    "$ref": "#/definitions/v1.WorkflowJobTarget"
                },
                "trigger_reason": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "workflow": {
                    "type": "string"
                }
            }
        },
        "cmd_apps_apis_rest_v1.WriteFileResponse": {
            "type": "object",
            "properties": {
                "len": {
                    "type": "integer"
                }
            }
        },
        "types.ConfigItem": {
            "type": "object",
            "properties": {
                "changed_at": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "types.DocumentProperties": {
            "type": "object",
            "properties": {
                "abstract": {
                    "description": "content",
                    "type": "string"
                },
                "author": {
                    "description": "papers",
                    "type": "string"
                },
                "headerImage": {
                    "type": "string"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "marked": {
                    "type": "boolean"
                },
                "notes": {
                    "type": "string"
                },
                "publishAt": {
                    "type": "integer"
                },
                "site_name": {
                    "type": "string"
                },
                "site_url": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "unread": {
                    "type": "boolean"
                },
                "url": {
                    "description": "web",
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "types.Properties": {
            "type": "object",
            "properties": {
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "site": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "url": {
                    "description": "web",
                    "type": "string"
                }
            }
        },
        "types.WorkflowLocalFileWatch": {
            "type": "object",
            "properties": {
                "cel_pattern": {
                    "type": "string"
                },
                "directory": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "file_pattern": {
                    "type": "string"
                },
                "file_types": {
                    "type": "string"
                },
                "max_file_size": {
                    "type": "integer"
                },
                "min_file_size": {
                    "type": "integer"
                }
            }
        },
        "types.WorkflowNode": {
            "type": "object",
            "properties": {
                "branches": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "cases": {
                    "description": "switch",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.WorkflowNodeCase"
                    }
                },
                "condition": {
                    "description": "if",
                    "type": "string"
                },
                "default": {
                    "type": "string"
                },
                "input": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "matrix": {
                    "description": "loop",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.WorkflowNodeMatrix"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "next": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.WorkflowNodeCase": {
            "type": "object",
            "properties": {
                "next": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "types.WorkflowNodeMatrix": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data defines variable mappings for matrix iteration\nKey is variable name, value is template reference to context data\nExample: {\"file_path\": \"{{ new_webpage.file_paths }}\"}",
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "types.WorkflowRssTrigger": {
            "type": "object"
        },
        "types.WorkflowTrigger": {
            "type": "object",
            "properties": {
                "interval": {
                    "type": "integer"
                },
                "local_file_watch": {
                    "$ref": "#/definitions/types.WorkflowLocalFileWatch"
                },
                "rss": {
                    "$ref": "#/definitions/types.WorkflowRssTrigger"
                }
            }
        },
        "v1.Access": {
            "type": "object",
            "properties": {
                "gid": {
                    "type": "integer"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "v1.ConfigResponse": {
            "type": "object",
            "properties": {
                "group": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "v1.CreateWorkflowRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "enable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.WorkflowNode"
                    }
                },
                "queue_name": {
                    "type": "string"
                },
                "trigger": {
                    "$ref": "#/definitions/types.WorkflowTrigger"
                }
            }
        },
        "v1.CreateWorkflowResponse": {
            "type": "object",
            "properties": {
                "workflow": {
                    "$ref": "#/definitions/cmd_apps_apis_rest_v1.WorkflowInfo"
                }
            }
        },
        "v1.DeleteConfigResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean"
                },
                "group": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "v1.DocumentPropertyResponse": {
            "type": "object",
            "properties": {
                "properties": {
                    "$ref": "#/definitions/cmd_apps_apis_rest_v1.DocumentProperty"
                }
            }
        },
        "v1.EntryDetailResponse": {
            "type": "object",
            "properties": {
                "entry": {
                    "$ref": "#/definitions/cmd_apps_apis_rest_v1.EntryDetail"
                }
            }
        },
        "v1.EntryResponse": {
            "type": "object",
            "properties": {
                "entry": {
                    "$ref": "#/definitions/cmd_apps_apis_rest_v1.EntryInfo"
                }
            }
        },
        "v1.FilterConfig": {
            "type": "object",
            "properties": {
                "cel_pattern": {
                    "type": "string"
                }
            }
        },
        "v1.GroupEntry": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.GroupEntry"
                    }
                },
                "name": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "v1.GroupTreeResponse": {
            "type": "object",
            "properties": {
                "root": {
                    "$ref": "#/definitions/v1.GroupEntry"
                }
            }
        },
        "v1.ListConfigResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ConfigItem"
                    }
                }
            }
        },
        "v1.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.PaginationInfo": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "v1.PropertyResponse": {
            "type": "object",
            "properties": {
                "properties": {
                    "$ref": "#/definitions/cmd_apps_apis_rest_v1.Property"
                }
            }
        },
        "v1.RssConfig": {
            "type": "object",
            "properties": {
                "feed": {
                    "type": "string"
                },
                "file_type": {
                    "type": "string"
                },
                "site_name": {
                    "type": "string"
                },
                "site_url": {
                    "type": "string"
                }
            }
        },
        "v1.SetConfigRequest": {
            "type": "object",
            "required": [
                "value"
            ],
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        },
        "v1.SetConfigResponse": {
            "type": "object",
            "properties": {
                "group": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "v1.UpdateWorkflowRequest": {
            "type": "object",
            "properties": {
                "enable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.WorkflowNode"
                    }
                },
                "queue_name": {
                    "type": "string"
                },
                "trigger": {
                    "$ref": "#/definitions/types.WorkflowTrigger"
                }
            }
        },
        "v1.WorkflowJobResponse": {
            "type": "object",
            "properties": {
                "job": {
                    "$ref": "#/definitions/cmd_apps_apis_rest_v1.WorkflowJobDetail"
                }
            }
        },
        "v1.WorkflowJobStep": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "v1.WorkflowJobTarget": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "v1.WorkflowResponse": {
            "type": "object",
            "properties": {
                "workflow": {
                    "$ref": "#/definitions/cmd_apps_apis_rest_v1.WorkflowInfo"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "NanaFS API",
	Description:      "NanaFS is a Reference Filing System API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
